name: SYNC-AWS-GOOGLE_WORKSPACE

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} 
          
      - name: Download JSON file from S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }} 
        run: |
          # The S3 bucket name is taken from a GitHub secret named 'S3_BUCKET_NAME'.
          # The file will be downloaded to the root of your runner's workspace as 'credentials.json'.
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }}/credentials.json ./credentials.json

      - name: Build Go Program using make
        run: make go-build 

      - name: Execute ssosync command
        run: |
          echo "Go program built successfully using make!"
          echo "Now executing ssosync with provided parameters..."
          ./ssosync \
            -t ${{ secrets.PROVISION_SECRET }} \
            -e ${{ secrets.SCIM_API_ENDPOINT }} \
            -u ${{ secrets.ADMIN_MAIL }} \
            --google-credentials credentials.json \
            --sync-method groups \
            --identity-store-id ${{ secrets.IDENTITY_STORE_ID }} \
            --debug \
            --region us-east-1
          echo "Google Workspace groups & Users sync with AWS completed"
